import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, } from 'react'
import { useState } from 'react'
import Layout from '../../components/Layout/Layout'
import Sidebar from '../../components/Layout/Sidebar'
import Calender from '../../components/StudentLayout/Calender'
import CreatedTasks from '../../components/TeacherLayout/CreatedTasks'
import { useAuth } from '../../lib/authContext'
import { db } from '../../lib/firebase'
import styles from '../../styles/Home.module.scss'

export default function teacher() {
    const [tasks, setTasks] = useState([])

    const { currentUser } = useAuth()

    const router = useRouter()

    useEffect(() => {
        if (!currentUser) {
            router.push("/login")
        }

        if (currentUser && currentUser.role === "student") {
            router.push("/student")
        }

        if (currentUser && currentUser.email) {
            db.collection("teachers").doc(currentUser.email).collection("createdExercises").get().then((querySnapshot) => {
                setTasks(querySnapshot.docs.map((doc) => ({ id: doc.id, data: doc.data() }))) 
            })
        }
    }, [currentUser])

    return (
        <Layout>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>


                <Sidebar />
                <div className={styles.innerContainer}>
                    <CreatedTasks tasks={tasks}/>
                    <Calender />
                </div>

            </div>
        </Layout>
    )
}
