import Head from 'next/head'
import Image from 'next/image'
import { useAuth } from '../lib/authContext'
import styles from '../styles/Home.module.scss'
import NextLink from "next/link"
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Layout from '../components/Layout/Layout'
import Tasks from '../components/StudentLayout/Tasks'
import Calender from '../components/StudentLayout/Calender'
import Sidebar from '../components/Layout/Sidebar'

export default function Home() {
  const { currentUser } = useAuth()

  const router = useRouter()

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </Layout>
  )
}
