import Head from 'next/head'
import { useAuth } from '../../lib/authContext'
import styles from '../../styles/Home.module.scss'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Layout from '../../components/Layout/Layout'
import Tasks from '../../components/StudentLayout/Tasks'
import Calender from '../../components/StudentLayout/Calender'
import Sidebar from '../../components/Layout/Sidebar'
import CompletedTasks from '../../components/StudentLayout/CompletedTasks'
import { db } from '../../lib/firebase'
import CoronaCases from '../../components/StudentLayout/CoronaCases'

export default function Home() {
    const [tasks, setTasks] = useState([])
    const [completedTasks, setCompletedTasks] = useState([])

    const { currentUser } = useAuth()

    const router = useRouter()

    useEffect(() => {
        if (!currentUser) {
            router.push("/login")
        }

        if (currentUser && currentUser.role === "teacher") {
            router.push("/teacher")
        }

        if (currentUser && currentUser.class) {
            db.collection("classes").doc(currentUser.class).collection("tasks").get().then((querySnapshot) => {
                setTasks(querySnapshot.docs.map((doc) => ({ id: doc.id, data: doc.data() }))) 
            })

            db.collection("students").doc(currentUser.email).collection("completedExercises").get().then((querySnapshot) => {
                setCompletedTasks(querySnapshot.docs.map((doc) => doc.id))
            })
        }
    }, [currentUser])

    return (
        <Layout>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Sidebar />
                <div className={styles.innerContainer}>
                    <div>
                        <Tasks tasks={tasks} completedTasks={completedTasks}/>
                        <CoronaCases />
                    </div>
                    <div className={styles.rightContainer}>
                        <Calender />
                        <CompletedTasks tasks={tasks.slice(0, 10)} completedTasks={completedTasks.slice(0, 10)}/>
                    </div>
                </div>
                
            </div>
        </Layout>
  )
}
